// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Q7GDR2tnFtzJd91WuC5uXYw31gVbNwU',
    appId: '1:810403540241:android:fe9166f48d4d979127b0b0',
    messagingSenderId: '810403540241',
    projectId: 'inkbattle0',
    storageBucket: 'inkbattle0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC64tNZ2zV3lHeK2tqOhAU0_m3L5S1PPjQ',
    appId: '1:810403540241:ios:a5c18bf7f8064dd127b0b0',
    messagingSenderId: '810403540241',
    projectId: 'inkbattle0',
    storageBucket: 'inkbattle0.firebasestorage.app',
    androidClientId: '810403540241-0ntkirbh1q64qcc7th5vscin3094coj7.apps.googleusercontent.com',
    iosClientId: '810403540241-jn3ngisp6peftdoofqko3b3u9qfsk2g7.apps.googleusercontent.com',
    iosBundleId: 'com.inkbattle.app',
  );
}
